//
// DeleteService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteService: Codable, JSONEncodable, Hashable {

    public var serviceProviderEntityId: String
    public var tokens: [TokenRepresentation]?

    public init(serviceProviderEntityId: String, tokens: [TokenRepresentation]? = nil) {
        self.serviceProviderEntityId = serviceProviderEntityId
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serviceProviderEntityId
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(serviceProviderEntityId, forKey: .serviceProviderEntityId)
        try container.encodeIfPresent(tokens, forKey: .tokens)
    }
}

