//
// EduIDInstitutionPseudonym.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EduIDInstitutionPseudonym: Codable, JSONEncodable, Hashable {

    /** Must be pre-provisioned in Manage for a valid IdP */
    public var brinCode: String
    /** Previous assigned eduID scoped on external remote API user */
    public var eduID: String

    public init(brinCode: String, eduID: String) {
        self.brinCode = brinCode
        self.eduID = eduID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brinCode
        case eduID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brinCode, forKey: .brinCode)
        try container.encode(eduID, forKey: .eduID)
    }
}

