//
// EduIDProvision.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EduIDProvision: Codable, JSONEncodable, Hashable {

    public var eduIDValue: String
    public var institutionGUID: String

    public init(eduIDValue: String, institutionGUID: String) {
        self.eduIDValue = eduIDValue
        self.institutionGUID = institutionGUID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eduIDValue
        case institutionGUID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eduIDValue, forKey: .eduIDValue)
        try container.encode(institutionGUID, forKey: .institutionGUID)
    }
}

