//
// GeneratedBackupCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeneratedBackupCode: Codable, JSONEncodable, Hashable {

    public var redirect: String?
    public var recoveryCode: String?

    public init(redirect: String? = nil, recoveryCode: String? = nil) {
        self.redirect = redirect
        self.recoveryCode = recoveryCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirect
        case recoveryCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(redirect, forKey: .redirect)
        try container.encodeIfPresent(recoveryCode, forKey: .recoveryCode)
    }
}

