//
// ManualResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ManualResponse: Codable, JSONEncodable, Hashable {

    public var sessionKey: String?
    public var response: String?

    public init(sessionKey: String? = nil, response: String? = nil) {
        self.sessionKey = sessionKey
        self.response = response
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionKey
        case response
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sessionKey, forKey: .sessionKey)
        try container.encodeIfPresent(response, forKey: .response)
    }
}

