//
// PhoneVerification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PhoneVerification: Codable, JSONEncodable, Hashable {

    public var phoneVerification: String?

    public init(phoneVerification: String? = nil) {
        self.phoneVerification = phoneVerification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phoneVerification
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phoneVerification, forKey: .phoneVerification)
    }
}

