//
// PublicKeyCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicKeyCredentials: Codable, JSONEncodable, Hashable {

    public var identifier: String?
    public var credential: String?
    public var name: String?
    public var createdAt: Int64?

    public init(identifier: String? = nil, credential: String? = nil, name: String? = nil, createdAt: Int64? = nil) {
        self.identifier = identifier
        self.credential = credential
        self.name = name
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifier
        case credential
        case name
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identifier, forKey: .identifier)
        try container.encodeIfPresent(credential, forKey: .credential)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

