//
// ServiceProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceProvider: Codable, JSONEncodable, Hashable {

    public var entityId: String?
    public var name: String?
    public var nameNl: String?
    public var institutionGuid: String?
    public var logoUrl: String?
    public var homeUrl: String?
    public var createdAt: Date?

    public init(entityId: String? = nil, name: String? = nil, nameNl: String? = nil, institutionGuid: String? = nil, logoUrl: String? = nil, homeUrl: String? = nil, createdAt: Date? = nil) {
        self.entityId = entityId
        self.name = name
        self.nameNl = nameNl
        self.institutionGuid = institutionGuid
        self.logoUrl = logoUrl
        self.homeUrl = homeUrl
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entityId
        case name
        case nameNl
        case institutionGuid
        case logoUrl
        case homeUrl
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entityId, forKey: .entityId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(nameNl, forKey: .nameNl)
        try container.encodeIfPresent(institutionGuid, forKey: .institutionGuid)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encodeIfPresent(homeUrl, forKey: .homeUrl)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

