//
// UpdateLinkedAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateLinkedAccountRequest: Codable, JSONEncodable, Hashable {

    public var eduPersonPrincipalName: String

    public init(eduPersonPrincipalName: String) {
        self.eduPersonPrincipalName = eduPersonPrincipalName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eduPersonPrincipalName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eduPersonPrincipalName, forKey: .eduPersonPrincipalName)
    }
}

