//
// UpdateUserNameRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateUserNameRequest: Codable, JSONEncodable, Hashable {

    public var chosenName: String?
    public var givenName: String?
    public var familyName: String?

    public init(chosenName: String? = nil, givenName: String? = nil, familyName: String? = nil) {
        self.chosenName = chosenName
        self.givenName = givenName
        self.familyName = familyName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chosenName
        case givenName
        case familyName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(chosenName, forKey: .chosenName)
        try container.encodeIfPresent(givenName, forKey: .givenName)
        try container.encodeIfPresent(familyName, forKey: .familyName)
    }
}

