//
// InviteControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class InviteControllerAPI {

    /**

     - parameter eduIDProvision: (body)  
     - returns: EduIDProvision
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func provisionEduid(eduIDProvision: EduIDProvision) async throws -> EduIDProvision {
        return try await provisionEduidWithRequestBuilder(eduIDProvision: eduIDProvision).execute().body
    }

    /**
     - POST /myconext/api/invite/provision-eduid
     - BASIC:
       - type: http
       - name: basic
     - parameter eduIDProvision: (body)  
     - returns: RequestBuilder<EduIDProvision> 
     */
    open class func provisionEduidWithRequestBuilder(eduIDProvision: EduIDProvision) -> RequestBuilder<EduIDProvision> {
        let localVariablePath = "/myconext/api/invite/provision-eduid"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: eduIDProvision)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EduIDProvision>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
