//
// ControlCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ControlCode: Codable, JSONEncodable, Hashable {

    static let firstNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let lastNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let dayOfBirthRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var firstName: String
    public var lastName: String
    public var dayOfBirth: String
    public var code: String?
    public var documentId: String?
    public var createdAt: Int64?
    public var userUid: String?

    public init(firstName: String, lastName: String, dayOfBirth: String, code: String? = nil, documentId: String? = nil, createdAt: Int64? = nil, userUid: String? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.dayOfBirth = dayOfBirth
        self.code = code
        self.documentId = documentId
        self.createdAt = createdAt
        self.userUid = userUid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case dayOfBirth
        case code
        case documentId
        case createdAt
        case userUid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(dayOfBirth, forKey: .dayOfBirth)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(documentId, forKey: .documentId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(userUid, forKey: .userUid)
    }
}

