//
// CreateEduIDResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateEduIDResponse: Codable, JSONEncodable, Hashable {

    public var status: Int?
    public var hash: String?

    public init(status: Int? = nil, hash: String? = nil) {
        self.status = status
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(hash, forKey: .hash)
    }
}

