//
// OneTimeLoginCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OneTimeLoginCode: Codable, JSONEncodable, Hashable {

    public var code: String?
    public var createdAt: Int64?
    public var delay: Int64?
    public var expired: Bool?
    public var codeAlmostExpired: Bool?

    public init(code: String? = nil, createdAt: Int64? = nil, delay: Int64? = nil, expired: Bool? = nil, codeAlmostExpired: Bool? = nil) {
        self.code = code
        self.createdAt = createdAt
        self.delay = delay
        self.expired = expired
        self.codeAlmostExpired = codeAlmostExpired
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case createdAt
        case delay
        case expired
        case codeAlmostExpired
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(expired, forKey: .expired)
        try container.encodeIfPresent(codeAlmostExpired, forKey: .codeAlmostExpired)
    }
}

