//
// PollAuthenticationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PollAuthenticationResult: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var redirect: String?
    public var hash: String?
    public var suspendedUntil: Int64?

    public init(status: String? = nil, redirect: String? = nil, hash: String? = nil, suspendedUntil: Int64? = nil) {
        self.status = status
        self.redirect = redirect
        self.hash = hash
        self.suspendedUntil = suspendedUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case redirect
        case hash
        case suspendedUntil
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(redirect, forKey: .redirect)
        try container.encodeIfPresent(hash, forKey: .hash)
        try container.encodeIfPresent(suspendedUntil, forKey: .suspendedUntil)
    }
}

