//
// Registration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Registration: Codable, JSONEncodable, Hashable {

    public var created: Int64?
    public var updated: Int64?
    public var notificationAddress: String?
    public var notificationType: String?
    public var phoneNumber: String?
    public var phoneVerified: Bool?
    public var recoveryCode: Bool?
    public var status: String?

    public init(created: Int64? = nil, updated: Int64? = nil, notificationAddress: String? = nil, notificationType: String? = nil, phoneNumber: String? = nil, phoneVerified: Bool? = nil, recoveryCode: Bool? = nil, status: String? = nil) {
        self.created = created
        self.updated = updated
        self.notificationAddress = notificationAddress
        self.notificationType = notificationType
        self.phoneNumber = phoneNumber
        self.phoneVerified = phoneVerified
        self.recoveryCode = recoveryCode
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created
        case updated
        case notificationAddress
        case notificationType
        case phoneNumber
        case phoneVerified
        case recoveryCode
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(notificationAddress, forKey: .notificationAddress)
        try container.encodeIfPresent(notificationType, forKey: .notificationType)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(phoneVerified, forKey: .phoneVerified)
        try container.encodeIfPresent(recoveryCode, forKey: .recoveryCode)
        try container.encodeIfPresent(status, forKey: .status)
    }
}
