//
// Scope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Scope: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var descriptions: [String: String]?

    public init(name: String? = nil, descriptions: [String: String]? = nil) {
        self.name = name
        self.descriptions = descriptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case descriptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(descriptions, forKey: .descriptions)
    }
}

