//
// StartEnrollment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StartEnrollment: Codable, JSONEncodable, Hashable {

    public var enrollmentKey: String?
    public var url: String?
    public var qrcode: String?

    public init(enrollmentKey: String? = nil, url: String? = nil, qrcode: String? = nil) {
        self.enrollmentKey = enrollmentKey
        self.url = url
        self.qrcode = qrcode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enrollmentKey
        case url
        case qrcode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enrollmentKey, forKey: .enrollmentKey)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(qrcode, forKey: .qrcode)
    }
}

