//
// VerifyOneTimeLoginCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyOneTimeLoginCode: Codable, JSONEncodable, Hashable {

    static let codeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var code: String
    public var authenticationRequestId: String?
    public var hash: String?

    public init(code: String, authenticationRequestId: String? = nil, hash: String? = nil) {
        self.code = code
        self.authenticationRequestId = authenticationRequestId
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case authenticationRequestId
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(authenticationRequestId, forKey: .authenticationRequestId)
        try container.encodeIfPresent(hash, forKey: .hash)
    }
}

